# https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: Check Cloud-Commands
on:
  pull_request:
    paths:
      - "cmd/**"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Action Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          path: "./cmd" # Optional.
          pattern: "*" # Optional.
          exclude: "./files" # Optional.
          fail_on_error: true
          shellcheck_flags: "-e SC2002,SC2126,SC2140"
      - name: Slack Notification for failed Build.
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: "danger"
          SLACK_ICON: ""
          SLACK_TITLE: Failed check
          SLACK_MESSAGE: |
            This Github Actions workflow failed check.
          SLACK_USERNAME: y-miyazaki
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
